sudo: false

language: node_js

cache:
  directories:
    - $HOME/.npm

notifications:
  email: false

node_js:
  - 8
  - 10

before_install:
  - npm install codecov.io coveralls
  - git config --global user.name "dmcho-dev"
  - git config --global user.email "dmcho.dev@gmail.com"

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npm run build
  - npm run travis-deploy-once "npm run semantic-release"

branches:
  only:
    - master
